/**
 * The 12 season palettes. Soft Autumn is the approved canvas report (project/Report.dc.html on
 * https://claude.ai/artifact/Q83bgjLjtYk2sS1ovCffy3); the other 11 were approved as swatches on
 * https://claude.ai/artifact/5t696uuN9gV4kVNi24XKPX (2026-10-02).
 *
 * @see openspec/specs/season-palettes/spec.md
 */
import type { SeasonSlug } from "./seasons.ts";

export interface Swatch {
  name: string;
  /** `#RRGGBB`, uppercase. */
  hex: string;
}

export interface Palette {
  /** 24: worn near the face. */
  best: readonly Swatch[];
  avoid: readonly Swatch[];
  /** 6: with the 24 best, the 30 colors the product promises. */
  neutrals: readonly Swatch[];
  metals: readonly Swatch[];
  /** Metals to go easy on. */
  metalsAvoid: readonly Swatch[];
  lips: readonly Swatch[];
  blush: readonly Swatch[];
  eyes: readonly Swatch[];
  hair: readonly Swatch[];
  /** A best color and a color to avoid, shown side by side on the face. */
  draping: { best: Swatch; worst: Swatch };
  /**
   * 6, from `best` and `neutrals`, in the order surfaces show them; a surface showing fewer shows
   * the first. Soft Autumn's are the canvas share card's; the other 11 were approved as swatches on
   * https://claude.ai/artifact/K24H42V67Uc7MkRs8p95y9 (2026-10-07).
   */
  highlights: readonly Swatch[];
}

export const PALETTES: Record<SeasonSlug, Palette> = {
  "light-spring": {
    best: [
      { name: "Peach", hex: "#F5B88F" },
      { name: "Apricot", hex: "#F3A66E" },
      { name: "Light Coral", hex: "#F08A7A" },
      { name: "Salmon Pink", hex: "#F29A8E" },
      { name: "Warm Pink", hex: "#EE8FA0" },
      { name: "Clear Coral", hex: "#F07560" },
      { name: "Watermelon", hex: "#EC6F78" },
      { name: "Coral Red", hex: "#E8604F" },
      { name: "Buttercup", hex: "#F6D46B" },
      { name: "Pale Daffodil", hex: "#F7E08A" },
      { name: "Light Gold", hex: "#E9C46A" },
      { name: "Light Camel", hex: "#D6B285" },
      { name: "Golden Tan", hex: "#CFA36A" },
      { name: "Spring Green", hex: "#9CCB72" },
      { name: "Light Moss", hex: "#B5C580" },
      { name: "Mint", hex: "#A8DFC1" },
      { name: "Light Jade", hex: "#6CC4A4" },
      { name: "Light Warm Aqua", hex: "#7FD3C5" },
      { name: "Light Turquoise", hex: "#5CC4C9" },
      { name: "Sky Aqua", hex: "#7FC7E0" },
      { name: "Periwinkle", hex: "#8FA8E0" },
      { name: "Light Warm Navy", hex: "#4D6A9E" },
      { name: "Lilac", hex: "#B8A3D6" },
      { name: "Violet Mist", hex: "#A08ACB" },
    ],
    avoid: [
      { name: "Jet Black", hex: "#111111" },
      { name: "Burgundy", hex: "#6E1E30" },
      { name: "Charcoal", hex: "#36383C" },
      { name: "Olive Drab", hex: "#5B5A2E" },
      { name: "Dusty Mauve", hex: "#8E6E78" },
      { name: "Deep Plum", hex: "#4A1F3D" },
    ],
    neutrals: [
      { name: "Ivory", hex: "#F8F1E0" },
      { name: "Cream Beige", hex: "#EBDCC0" },
      { name: "Golden Beige", hex: "#D8BC92" },
      { name: "Light Taupe", hex: "#BFAA90" },
      { name: "Warm Stone", hex: "#A89A88" },
      { name: "Soft Navy", hex: "#4F6188" },
    ],
    metals: [
      { name: "Light Gold", hex: "#E3C57A" },
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Rose Gold", hex: "#D4A08A" },
      { name: "Champagne", hex: "#E6D3A8" },
    ],
    metalsAvoid: [
      { name: "Gunmetal", hex: "#5A5D63" },
      { name: "Oxidized Silver", hex: "#8C8F94" },
    ],
    lips: [
      { name: "Peach Nude", hex: "#E3A08A" },
      { name: "Coral Pink", hex: "#EE8678" },
      { name: "Petal Pink", hex: "#E27D86" },
    ],
    blush: [
      { name: "Peach", hex: "#F0A58A" },
      { name: "Apricot Glow", hex: "#F2A27D" },
      { name: "Light Coral", hex: "#EE9A8F" },
    ],
    eyes: [
      { name: "Champagne", hex: "#E4CDA8" },
      { name: "Light Bronze", hex: "#B88A5E" },
      { name: "Soft Aqua", hex: "#7DBFB4" },
    ],
    hair: [
      { name: "Golden Blonde", hex: "#D7B377" },
      { name: "Strawberry Blonde", hex: "#D49A6A" },
      { name: "Honey Blonde", hex: "#C9A064" },
    ],
    draping: {
      best: { name: "Peach", hex: "#F5B88F" },
      worst: { name: "Burgundy", hex: "#6E1E30" },
    },
    highlights: [
      { name: "Peach", hex: "#F5B88F" },
      { name: "Light Turquoise", hex: "#5CC4C9" },
      { name: "Buttercup", hex: "#F6D46B" },
      { name: "Warm Pink", hex: "#EE8FA0" },
      { name: "Spring Green", hex: "#9CCB72" },
      { name: "Light Taupe", hex: "#BFAA90" },
    ],
  },
  "true-spring": {
    best: [
      { name: "Coral", hex: "#F26B4F" },
      { name: "Poppy Red", hex: "#E0452F" },
      { name: "Salmon", hex: "#F38B73" },
      { name: "Peach", hex: "#F7AE87" },
      { name: "Warm Pink", hex: "#F27A8A" },
      { name: "Tangerine", hex: "#F28C28" },
      { name: "Marigold", hex: "#F2B134" },
      { name: "Golden Yellow", hex: "#F5C518" },
      { name: "Daffodil", hex: "#F7D84A" },
      { name: "Camel", hex: "#C99A5B" },
      { name: "Golden Brown", hex: "#A86B2D" },
      { name: "Cinnamon", hex: "#B5602C" },
      { name: "Golden Olive", hex: "#9A8A2E" },
      { name: "Lime", hex: "#A5C83F" },
      { name: "Grass Green", hex: "#5FA840" },
      { name: "Kelly Green", hex: "#3C9A4D" },
      { name: "Bright Jade", hex: "#00A383" },
      { name: "Turquoise", hex: "#18B0B0" },
      { name: "Warm Aqua", hex: "#45C2B6" },
      { name: "Teal Blue", hex: "#1D8A99" },
      { name: "Cornflower", hex: "#6A8FD9" },
      { name: "Bright Periwinkle", hex: "#8C8EE0" },
      { name: "Clear Navy", hex: "#2E4A8C" },
      { name: "Violet", hex: "#8A5DBF" },
    ],
    avoid: [
      { name: "Jet Black", hex: "#111111" },
      { name: "Icy Grey", hex: "#D9DDE3" },
      { name: "Dusty Rose", hex: "#C4A0A5" },
      { name: "Burgundy", hex: "#6E1E30" },
      { name: "Fuchsia", hex: "#CC2A7E" },
      { name: "Charcoal Grey", hex: "#36383C" },
    ],
    neutrals: [
      { name: "Ivory", hex: "#F6EED8" },
      { name: "Warm Beige", hex: "#E3CBA3" },
      { name: "Light Camel", hex: "#CFAE80" },
      { name: "Caramel", hex: "#A8763E" },
      { name: "Milk Chocolate", hex: "#7E5534" },
      { name: "Warm Navy", hex: "#2F4066" },
    ],
    metals: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Polished Gold", hex: "#E1B84B" },
      { name: "Brass", hex: "#B5975A" },
      { name: "Copper", hex: "#B87333" },
    ],
    metalsAvoid: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Platinum", hex: "#DCDDDF" },
    ],
    lips: [
      { name: "Coral Red", hex: "#E0563F" },
      { name: "Warm Peach", hex: "#E88A6B" },
      { name: "Tomato Red", hex: "#D9432E" },
    ],
    blush: [
      { name: "Warm Peach", hex: "#F09A78" },
      { name: "Coral", hex: "#EE8669" },
      { name: "Apricot", hex: "#F2A779" },
    ],
    eyes: [
      { name: "Golden Bronze", hex: "#A8773D" },
      { name: "Warm Teal", hex: "#2F8C83" },
      { name: "Copper", hex: "#B5652E" },
    ],
    hair: [
      { name: "Golden Copper", hex: "#B06A33" },
      { name: "Honey Gold", hex: "#C99A4E" },
      { name: "Warm Chestnut", hex: "#8A5530" },
    ],
    draping: {
      best: { name: "Coral", hex: "#F26B4F" },
      worst: { name: "Burgundy", hex: "#6E1E30" },
    },
    highlights: [
      { name: "Coral", hex: "#F26B4F" },
      { name: "Turquoise", hex: "#18B0B0" },
      { name: "Marigold", hex: "#F2B134" },
      { name: "Warm Pink", hex: "#F27A8A" },
      { name: "Kelly Green", hex: "#3C9A4D" },
      { name: "Caramel", hex: "#A8763E" },
    ],
  },
  "bright-spring": {
    best: [
      { name: "Bright Coral", hex: "#FF6F5E" },
      { name: "Clear Red", hex: "#E8312F" },
      { name: "Hot Coral Pink", hex: "#F25C7A" },
      { name: "Hot Pink", hex: "#E8407F" },
      { name: "Bright Peach", hex: "#FF9E7A" },
      { name: "Bright Orange", hex: "#F57B20" },
      { name: "Mango", hex: "#FFA62B" },
      { name: "Sunflower", hex: "#FFC20E" },
      { name: "Lemon Sorbet", hex: "#F7E35A" },
      { name: "Bright Lime", hex: "#9BCF2E" },
      { name: "Kelly Green", hex: "#2EA84A" },
      { name: "Emerald", hex: "#009B77" },
      { name: "Bright Mint", hex: "#6FE0B0" },
      { name: "Bright Turquoise", hex: "#00B5C0" },
      { name: "Aqua", hex: "#3FD0D4" },
      { name: "Bright Teal", hex: "#00838F" },
      { name: "Bright Periwinkle", hex: "#6C7EE8" },
      { name: "Royal Blue", hex: "#2F5BD3" },
      { name: "Bright Navy", hex: "#1F3A8A" },
      { name: "Violet", hex: "#7B4FC9" },
      { name: "Orchid", hex: "#A05FC8" },
      { name: "Bright Lilac", hex: "#B48CE0" },
      { name: "Golden Tan", hex: "#D2A55E" },
      { name: "Camel", hex: "#C49A62" },
    ],
    avoid: [
      { name: "Dusty Rose", hex: "#C4A0A5" },
      { name: "Olive Drab", hex: "#6B6A3A" },
      { name: "Mushroom", hex: "#A08F7E" },
      { name: "Smoky Grey", hex: "#8A8A88" },
      { name: "Muted Sage", hex: "#9AA38C" },
      { name: "Rust Brown", hex: "#8A4B2C" },
    ],
    neutrals: [
      { name: "Bright Ivory", hex: "#FBF6E9" },
      { name: "Warm Sand", hex: "#E4CFA8" },
      { name: "Light Warm Grey", hex: "#C9C3B8" },
      { name: "Medium Grey", hex: "#8C8C8A" },
      { name: "Chocolate", hex: "#5A3A26" },
      { name: "Ink Navy", hex: "#1D2A4D" },
    ],
    metals: [
      { name: "Polished Gold", hex: "#E1B84B" },
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Rose Gold", hex: "#D9A08A" },
      { name: "Brass", hex: "#C9A24A" },
    ],
    metalsAvoid: [
      { name: "Antique Bronze", hex: "#6E5434" },
      { name: "Pewter", hex: "#8E9196" },
    ],
    lips: [
      { name: "Clear Coral", hex: "#F0604F" },
      { name: "Hot Coral", hex: "#F2506A" },
      { name: "Warm Red", hex: "#D9342B" },
    ],
    blush: [
      { name: "Bright Peach", hex: "#FF9A80" },
      { name: "Warm Pink", hex: "#F27A8A" },
      { name: "Coral Pink", hex: "#F48A7A" },
    ],
    eyes: [
      { name: "Bright Teal", hex: "#00838F" },
      { name: "Golden Bronze", hex: "#A8773D" },
      { name: "Violet Plum", hex: "#6B3F8E" },
    ],
    hair: [
      { name: "Golden Chestnut", hex: "#8A5530" },
      { name: "Bright Copper", hex: "#B35A2A" },
      { name: "Warm Dark Brown", hex: "#4A3020" },
    ],
    draping: {
      best: { name: "Bright Coral", hex: "#FF6F5E" },
      worst: { name: "Olive Drab", hex: "#6B6A3A" },
    },
    highlights: [
      { name: "Bright Coral", hex: "#FF6F5E" },
      { name: "Bright Turquoise", hex: "#00B5C0" },
      { name: "Sunflower", hex: "#FFC20E" },
      { name: "Hot Pink", hex: "#E8407F" },
      { name: "Emerald", hex: "#009B77" },
      { name: "Ink Navy", hex: "#1D2A4D" },
    ],
  },
  "light-summer": {
    best: [
      { name: "Powder Blue", hex: "#A9C6E8" },
      { name: "Sky Blue", hex: "#8DB8E2" },
      { name: "Light Periwinkle", hex: "#B5C0EC" },
      { name: "Periwinkle", hex: "#9BA8DE" },
      { name: "Cornflower", hex: "#7F9AD6" },
      { name: "Soft Denim", hex: "#6E8DB8" },
      { name: "Blue Mist", hex: "#9FB1C4" },
      { name: "Light Aqua", hex: "#9BD3D6" },
      { name: "Soft Teal", hex: "#6AAEAE" },
      { name: "Soft Jade", hex: "#78B5A0" },
      { name: "Seafoam", hex: "#8EC6B0" },
      { name: "Mint", hex: "#A8D8C2" },
      { name: "Lavender", hex: "#B9A9DB" },
      { name: "Lilac", hex: "#C8A9D6" },
      { name: "Soft Violet", hex: "#9C8CC4" },
      { name: "Soft Plum", hex: "#9A6E95" },
      { name: "Orchid Pink", hex: "#D69BC4" },
      { name: "Mauve Pink", hex: "#C792A8" },
      { name: "Rose Pink", hex: "#E8A3B7" },
      { name: "Powder Pink", hex: "#F2C1CF" },
      { name: "Soft Watermelon", hex: "#E68A96" },
      { name: "Raspberry Sorbet", hex: "#D16A8A" },
      { name: "Soft Cherry", hex: "#D35A6E" },
      { name: "Light Lemon", hex: "#F3E8A0" },
    ],
    avoid: [
      { name: "Jet Black", hex: "#111111" },
      { name: "Orange", hex: "#F57B20" },
      { name: "Mustard", hex: "#BF9A4A" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Olive", hex: "#7B7848" },
      { name: "Chocolate Brown", hex: "#4A2E1E" },
    ],
    neutrals: [
      { name: "Soft White", hex: "#F5F3EF" },
      { name: "Light Grey", hex: "#D4D5D8" },
      { name: "Rose Beige", hex: "#D9C4BD" },
      { name: "Rose Taupe", hex: "#A39A96" },
      { name: "Grey Blue", hex: "#7D8A9C" },
      { name: "Soft Navy", hex: "#4A5A86" },
    ],
    metals: [
      { name: "Silver", hex: "#C0C3C8" },
      { name: "Platinum", hex: "#DCDDDF" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Rose Gold", hex: "#D2A79A" },
    ],
    metalsAvoid: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Copper", hex: "#B87333" },
    ],
    lips: [
      { name: "Rose Pink", hex: "#D98A9C" },
      { name: "Soft Berry", hex: "#B8607A" },
      { name: "Watermelon", hex: "#E07884" },
    ],
    blush: [
      { name: "Pink Petal", hex: "#F0B3C0" },
      { name: "Cool Rose", hex: "#E09AAA" },
      { name: "Soft Plum Pink", hex: "#C98AA5" },
    ],
    eyes: [
      { name: "Soft Grey", hex: "#A3A6AC" },
      { name: "Lavender Taupe", hex: "#9D8E9E" },
      { name: "Soft Navy", hex: "#4A5A86" },
    ],
    hair: [
      { name: "Ash Blonde", hex: "#C2B394" },
      { name: "Pale Ash Blonde", hex: "#D6CBB1" },
      { name: "Light Ash Brown", hex: "#8C7B66" },
    ],
    draping: {
      best: { name: "Powder Blue", hex: "#A9C6E8" },
      worst: { name: "Mustard", hex: "#BF9A4A" },
    },
    highlights: [
      { name: "Powder Blue", hex: "#A9C6E8" },
      { name: "Soft Teal", hex: "#6AAEAE" },
      { name: "Light Lemon", hex: "#F3E8A0" },
      { name: "Rose Pink", hex: "#E8A3B7" },
      { name: "Lavender", hex: "#B9A9DB" },
      { name: "Rose Taupe", hex: "#A39A96" },
    ],
  },
  "true-summer": {
    best: [
      { name: "Soft Blue", hex: "#6F95C8" },
      { name: "Sky Blue", hex: "#8FB3DB" },
      { name: "Denim Blue", hex: "#5C7FAE" },
      { name: "Cadet Blue", hex: "#4F6F96" },
      { name: "Slate Blue", hex: "#66779A" },
      { name: "Periwinkle", hex: "#8592CF" },
      { name: "Lavender", hex: "#A99BD0" },
      { name: "Soft Violet", hex: "#8A79BD" },
      { name: "Blue Teal", hex: "#3F8A94" },
      { name: "Blue Spruce", hex: "#3E6B73" },
      { name: "Cool Jade", hex: "#4FA08A" },
      { name: "Sea Green", hex: "#5FA89A" },
      { name: "Mint", hex: "#A0D3C0" },
      { name: "Cool Pink", hex: "#E4A2BA" },
      { name: "Rose Pink", hex: "#D9849C" },
      { name: "Watermelon", hex: "#E06C7C" },
      { name: "Cool Cherry", hex: "#C24156" },
      { name: "Raspberry", hex: "#B8456B" },
      { name: "Berry", hex: "#9C3F63" },
      { name: "Soft Fuchsia", hex: "#C85A94" },
      { name: "Orchid", hex: "#B87BB5" },
      { name: "Plum", hex: "#7D4A72" },
      { name: "Mulberry", hex: "#6E3A5E" },
      { name: "Light Lemon", hex: "#EFE6A4" },
    ],
    avoid: [
      { name: "Orange", hex: "#F57B20" },
      { name: "Golden Yellow", hex: "#F5C518" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Olive Green", hex: "#7B7848" },
      { name: "Warm Brown", hex: "#7A4A2A" },
    ],
    neutrals: [
      { name: "Soft White", hex: "#F4F2EE" },
      { name: "Light Cool Grey", hex: "#C8CBD0" },
      { name: "Cool Taupe", hex: "#8F8582" },
      { name: "Rose Brown", hex: "#8A6E6E" },
      { name: "Charcoal Blue", hex: "#3D4655" },
      { name: "Navy", hex: "#2F3F66" },
    ],
    metals: [
      { name: "Silver", hex: "#C0C3C8" },
      { name: "Platinum", hex: "#DCDDDF" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Pewter", hex: "#8E9196" },
    ],
    metalsAvoid: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Brass", hex: "#B5975A" },
    ],
    lips: [
      { name: "Cool Rose", hex: "#C76E85" },
      { name: "Raspberry", hex: "#B04568" },
      { name: "Berry Pink", hex: "#C25A7E" },
    ],
    blush: [
      { name: "Cool Pink", hex: "#E39AB0" },
      { name: "Rose", hex: "#D08399" },
      { name: "Soft Plum", hex: "#B57A99" },
    ],
    eyes: [
      { name: "Cool Grey", hex: "#8E9299" },
      { name: "Slate Blue", hex: "#66779A" },
      { name: "Plum Taupe", hex: "#7E6876" },
    ],
    hair: [
      { name: "Ash Brown", hex: "#75685A" },
      { name: "Cool Light Brown", hex: "#8E7E6A" },
      { name: "Ash Blonde", hex: "#B5A88E" },
    ],
    draping: {
      best: { name: "Soft Blue", hex: "#6F95C8" },
      worst: { name: "Orange", hex: "#F57B20" },
    },
    highlights: [
      { name: "Soft Blue", hex: "#6F95C8" },
      { name: "Sea Green", hex: "#5FA89A" },
      { name: "Rose Pink", hex: "#D9849C" },
      { name: "Lavender", hex: "#A99BD0" },
      { name: "Plum", hex: "#7D4A72" },
      { name: "Cool Taupe", hex: "#8F8582" },
    ],
  },
  "soft-summer": {
    best: [
      { name: "Dusty Blue", hex: "#7D93AE" },
      { name: "Pewter Blue", hex: "#8899A8" },
      { name: "Slate Blue", hex: "#6A7B96" },
      { name: "Denim", hex: "#5E7491" },
      { name: "Muted Teal Blue", hex: "#5B7C8A" },
      { name: "Soft Navy", hex: "#3E4E68" },
      { name: "Smoky Teal", hex: "#5C8686" },
      { name: "Blue Spruce", hex: "#456A70" },
      { name: "Soft Spruce", hex: "#4D6B6A" },
      { name: "Soft Jade", hex: "#6E9A8A" },
      { name: "Grey Green", hex: "#8A9C8E" },
      { name: "Seafoam Grey", hex: "#9DB8B0" },
      { name: "Powder Rose", hex: "#D4B0B4" },
      { name: "Dusty Rose", hex: "#C4979E" },
      { name: "Rosewood Pink", hex: "#B7737F" },
      { name: "Cocoa Rose", hex: "#9E7A7A" },
      { name: "Rose Brown", hex: "#8E6A6E" },
      { name: "Mauve", hex: "#A07D8C" },
      { name: "Raspberry Mist", hex: "#A85C78" },
      { name: "Soft Berry", hex: "#9C5470" },
      { name: "Dusty Plum", hex: "#7E5C74" },
      { name: "Muted Aubergine", hex: "#5E4558" },
      { name: "Soft Lavender", hex: "#A89CBB" },
      { name: "Grey Violet", hex: "#8A80A6" },
    ],
    avoid: [
      { name: "Jet Black", hex: "#111111" },
      { name: "Optic White", hex: "#FDFDFD" },
      { name: "Orange", hex: "#F57B20" },
      { name: "Bright Yellow", hex: "#F5D30F" },
      { name: "Kelly Green", hex: "#2EA84A" },
      { name: "Rust", hex: "#A65E3E" },
    ],
    neutrals: [
      { name: "Soft White", hex: "#EEEBE6" },
      { name: "Light Taupe Grey", hex: "#BDB5AE" },
      { name: "Rose Taupe", hex: "#9C8B87" },
      { name: "Cool Cocoa", hex: "#6E5E5C" },
      { name: "Charcoal", hex: "#4A4C52" },
      { name: "Grey Navy", hex: "#3C4558" },
    ],
    metals: [
      { name: "Brushed Silver", hex: "#B5B8BC" },
      { name: "Pewter", hex: "#8E9196" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Rose Gold", hex: "#C9A091" },
    ],
    metalsAvoid: [
      { name: "Polished Gold", hex: "#E1B84B" },
      { name: "Copper", hex: "#B87333" },
    ],
    lips: [
      { name: "Dusty Rose", hex: "#B97C86" },
      { name: "Mauve Berry", hex: "#9C5E74" },
      { name: "Soft Raspberry", hex: "#A85C78" },
    ],
    blush: [
      { name: "Soft Rose", hex: "#D29BA4" },
      { name: "Dusty Mauve Pink", hex: "#C08E9C" },
      { name: "Muted Plum", hex: "#A87C90" },
    ],
    eyes: [
      { name: "Taupe Grey", hex: "#8E8582" },
      { name: "Smoky Plum", hex: "#6E5466" },
      { name: "Slate", hex: "#6A7685" },
    ],
    hair: [
      { name: "Ash Brown", hex: "#75685A" },
      { name: "Mousy Ash", hex: "#8A7F70" },
      { name: "Cool Mocha", hex: "#5E5048" },
    ],
    draping: {
      best: { name: "Dusty Rose", hex: "#C4979E" },
      worst: { name: "Orange", hex: "#F57B20" },
    },
    highlights: [
      { name: "Dusty Rose", hex: "#C4979E" },
      { name: "Smoky Teal", hex: "#5C8686" },
      { name: "Dusty Blue", hex: "#7D93AE" },
      { name: "Grey Violet", hex: "#8A80A6" },
      { name: "Grey Green", hex: "#8A9C8E" },
      { name: "Rose Taupe", hex: "#9C8B87" },
    ],
  },
  "soft-autumn": {
    best: [
      { name: "Soft Coral", hex: "#D88E77" },
      { name: "Dusty Rose", hex: "#C4918A" },
      { name: "Mauve", hex: "#9C7A82" },
      { name: "Rosewood", hex: "#8E5A55" },
      { name: "Plum Brown", hex: "#6E4D4F" },
      { name: "Copper", hex: "#B87A4D" },
      { name: "Terracotta", hex: "#B4694F" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Burnt Terracotta", hex: "#A4583F" },
      { name: "Brick", hex: "#9B5544" },
      { name: "Wheat", hex: "#D8C3A0" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Honey", hex: "#C99A5B" },
      { name: "Mustard", hex: "#BF9A4A" },
      { name: "Khaki", hex: "#A9A27A" },
      { name: "Sage", hex: "#8E9A78" },
      { name: "Olive", hex: "#7B7848" },
      { name: "Moss", hex: "#66704A" },
      { name: "Jade", hex: "#5E8C7A" },
      { name: "Pine", hex: "#3F5A4C" },
      { name: "Denim Smoke", hex: "#6C7E8A" },
      { name: "Slate Teal", hex: "#577C80" },
      { name: "Deep Teal", hex: "#4C7774" },
      { name: "Spruce", hex: "#3E6366" },
    ],
    avoid: [
      { name: "Optic White", hex: "#FDFDFD" },
      { name: "Icy Pink", hex: "#F1D3E2" },
      { name: "Lemon Yellow", hex: "#F2E14C" },
      { name: "Fuchsia", hex: "#CC2A7E" },
      { name: "Electric Blue", hex: "#2457D6" },
      { name: "Jet Black", hex: "#111111" },
    ],
    neutrals: [
      { name: "Ivory Cream", hex: "#EDE3CF" },
      { name: "Oatmeal", hex: "#D9CDB8" },
      { name: "Mushroom", hex: "#A08F7E" },
      { name: "Warm Taupe", hex: "#8C7766" },
      { name: "Cocoa", hex: "#6A5145" },
      { name: "Espresso", hex: "#4A3A33" },
    ],
    metals: [
      { name: "Brushed Gold", hex: "#C8A464" },
      { name: "Rose Gold", hex: "#B98A72" },
      { name: "Bronze", hex: "#8C6A43" },
      { name: "Antique Brass", hex: "#A88A5A" },
    ],
    metalsAvoid: [
      { name: "Polished Silver", hex: "#C7CBD1" },
      { name: "Platinum", hex: "#DCDDDF" },
    ],
    lips: [
      { name: "Terracotta Nude", hex: "#B06B5A" },
      { name: "Warm Rosewood", hex: "#94574F" },
      { name: "Brick Rose", hex: "#A2564A" },
    ],
    blush: [
      { name: "Soft Peach", hex: "#D9967E" },
      { name: "Dusty Apricot", hex: "#CC9277" },
      { name: "Muted Rose", hex: "#BF8780" },
    ],
    eyes: [
      { name: "Soft Bronze", hex: "#8F6B48" },
      { name: "Olive Khaki", hex: "#7E7A52" },
      { name: "Warm Taupe", hex: "#8C7766" },
    ],
    hair: [
      { name: "Golden Brown", hex: "#7A5A3C" },
      { name: "Soft Caramel", hex: "#A57B52" },
      { name: "Honey Bronde", hex: "#A8875F" },
    ],
    draping: {
      best: { name: "Terracotta", hex: "#B4694F" },
      worst: { name: "Fuchsia", hex: "#CC2A7E" },
    },
    highlights: [
      { name: "Terracotta", hex: "#B4694F" },
      { name: "Deep Teal", hex: "#4C7774" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Dusty Rose", hex: "#C4918A" },
      { name: "Olive", hex: "#7B7848" },
      { name: "Mushroom", hex: "#A08F7E" },
    ],
  },
  "true-autumn": {
    best: [
      { name: "Pumpkin", hex: "#D2691E" },
      { name: "Burnt Orange", hex: "#CC5500" },
      { name: "Rust", hex: "#B7472A" },
      { name: "Spice Red", hex: "#C0402C" },
      { name: "Paprika", hex: "#A8392A" },
      { name: "Terracotta", hex: "#C0643F" },
      { name: "Copper", hex: "#B5652E" },
      { name: "Salmon", hex: "#E07B5A" },
      { name: "Peach", hex: "#E8A07A" },
      { name: "Saffron", hex: "#E2A33B" },
      { name: "Golden Yellow", hex: "#DDAA33" },
      { name: "Mustard", hex: "#CC9B2B" },
      { name: "Camel", hex: "#B8894F" },
      { name: "Caramel", hex: "#A86A2E" },
      { name: "Golden Brown", hex: "#8B5A2B" },
      { name: "Mahogany", hex: "#6E2E1F" },
      { name: "Avocado", hex: "#8A8E3A" },
      { name: "Olive", hex: "#7A7A2E" },
      { name: "Moss Green", hex: "#6B7A2E" },
      { name: "Forest Green", hex: "#3E5E34" },
      { name: "Jade", hex: "#4B8F6A" },
      { name: "Warm Teal", hex: "#2F7A72" },
      { name: "Peacock Teal", hex: "#1F6E6E" },
      { name: "Warm Plum", hex: "#6E3A3E" },
    ],
    avoid: [
      { name: "Icy Blue", hex: "#CFE3F2" },
      { name: "Fuchsia", hex: "#CC2A7E" },
      { name: "Bubblegum Pink", hex: "#F4A3C8" },
      { name: "Cool Grey", hex: "#9A9EA6" },
      { name: "Optic White", hex: "#FDFDFD" },
      { name: "Royal Purple", hex: "#5A2D91" },
    ],
    neutrals: [
      { name: "Cream", hex: "#F1E4C8" },
      { name: "Warm Beige", hex: "#D9BE94" },
      { name: "Camel Tan", hex: "#B88F5F" },
      { name: "Olive Khaki", hex: "#7F7347" },
      { name: "Coffee", hex: "#6A4A30" },
      { name: "Dark Chocolate", hex: "#3E2A1E" },
    ],
    metals: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Antique Gold", hex: "#B8963E" },
      { name: "Copper", hex: "#B87333" },
      { name: "Bronze", hex: "#8C6A43" },
    ],
    metalsAvoid: [
      { name: "Silver", hex: "#C0C0C0" },
      { name: "Platinum", hex: "#DCDDDF" },
    ],
    lips: [
      { name: "Brick Red", hex: "#A3412F" },
      { name: "Warm Terracotta", hex: "#B85A3E" },
      { name: "Burnt Coral", hex: "#C9604A" },
    ],
    blush: [
      { name: "Warm Peach", hex: "#E2936E" },
      { name: "Terracotta Blush", hex: "#C67658" },
      { name: "Apricot", hex: "#E3A06E" },
    ],
    eyes: [
      { name: "Bronze", hex: "#8C6A43" },
      { name: "Olive Moss", hex: "#6B6A35" },
      { name: "Copper Brown", hex: "#8A4E2A" },
    ],
    hair: [
      { name: "Auburn", hex: "#8A3E22" },
      { name: "Copper Red", hex: "#A64B28" },
      { name: "Golden Chestnut", hex: "#7A4A26" },
    ],
    draping: {
      best: { name: "Pumpkin", hex: "#D2691E" },
      worst: { name: "Bubblegum Pink", hex: "#F4A3C8" },
    },
    highlights: [
      { name: "Pumpkin", hex: "#D2691E" },
      { name: "Peacock Teal", hex: "#1F6E6E" },
      { name: "Mustard", hex: "#CC9B2B" },
      { name: "Salmon", hex: "#E07B5A" },
      { name: "Olive", hex: "#7A7A2E" },
      { name: "Camel Tan", hex: "#B88F5F" },
    ],
  },
  "deep-autumn": {
    best: [
      { name: "Deep Rust", hex: "#8F3B1F" },
      { name: "Burnt Orange", hex: "#C05A1E" },
      { name: "Tomato Red", hex: "#B8382A" },
      { name: "Chili", hex: "#9A2A22" },
      { name: "Brick Red", hex: "#8E3A2C" },
      { name: "Oxblood", hex: "#5E1F1F" },
      { name: "Mahogany", hex: "#6E2E1F" },
      { name: "Terracotta", hex: "#A9553A" },
      { name: "Deep Salmon", hex: "#C0664A" },
      { name: "Cinnamon", hex: "#8A4A22" },
      { name: "Golden Brown", hex: "#7A4E22" },
      { name: "Camel", hex: "#A9814F" },
      { name: "Saffron", hex: "#D19A2A" },
      { name: "Mustard", hex: "#B88A1F" },
      { name: "Antique Gold", hex: "#A88426" },
      { name: "Olive", hex: "#5E5A26" },
      { name: "Forest Green", hex: "#2F4A2A" },
      { name: "Hunter Green", hex: "#355E3B" },
      { name: "Warm Emerald", hex: "#1E6B4E" },
      { name: "Deep Teal", hex: "#1E5A5A" },
      { name: "Petrol Teal", hex: "#1F4F5E" },
      { name: "Teal Blue", hex: "#1F5F78" },
      { name: "Deep Plum", hex: "#5A2A40" },
      { name: "Aubergine", hex: "#4A2340" },
    ],
    avoid: [
      { name: "Pastel Pink", hex: "#F4C2D7" },
      { name: "Icy Blue", hex: "#CFE3F2" },
      { name: "Lavender", hex: "#C2B5E3" },
      { name: "Optic White", hex: "#FDFDFD" },
      { name: "Baby Yellow", hex: "#F7EBA0" },
      { name: "Dove Grey", hex: "#C9CBCF" },
    ],
    neutrals: [
      { name: "Cream", hex: "#EFE3C8" },
      { name: "Camel Beige", hex: "#C7A57C" },
      { name: "Taupe Brown", hex: "#7A6250" },
      { name: "Dark Olive", hex: "#3E3B22" },
      { name: "Chocolate", hex: "#4A2E1E" },
      { name: "Espresso", hex: "#2E201A" },
    ],
    metals: [
      { name: "Antique Gold", hex: "#B8963E" },
      { name: "Bronze", hex: "#8C6A43" },
      { name: "Copper", hex: "#B87333" },
      { name: "Burnished Brass", hex: "#9C7F3E" },
    ],
    metalsAvoid: [
      { name: "Polished Silver", hex: "#C7CBD1" },
      { name: "Platinum", hex: "#DCDDDF" },
    ],
    lips: [
      { name: "Brick", hex: "#8E3A2C" },
      { name: "Deep Terracotta", hex: "#9A4A35" },
      { name: "Chocolate Berry", hex: "#6E2E30" },
    ],
    blush: [
      { name: "Terracotta", hex: "#B8674A" },
      { name: "Warm Bronze", hex: "#A26A4A" },
      { name: "Deep Peach", hex: "#C77A5A" },
    ],
    eyes: [
      { name: "Dark Bronze", hex: "#6E4E2E" },
      { name: "Forest Olive", hex: "#4A4A26" },
      { name: "Deep Plum", hex: "#4E2A3A" },
    ],
    hair: [
      { name: "Dark Chocolate", hex: "#3E2618" },
      { name: "Mahogany Brown", hex: "#5A2A1E" },
      { name: "Deep Auburn", hex: "#6E2E1E" },
    ],
    draping: {
      best: { name: "Deep Rust", hex: "#8F3B1F" },
      worst: { name: "Pastel Pink", hex: "#F4C2D7" },
    },
    highlights: [
      { name: "Deep Rust", hex: "#8F3B1F" },
      { name: "Deep Teal", hex: "#1E5A5A" },
      { name: "Saffron", hex: "#D19A2A" },
      { name: "Deep Plum", hex: "#5A2A40" },
      { name: "Hunter Green", hex: "#355E3B" },
      { name: "Taupe Brown", hex: "#7A6250" },
    ],
  },
  "deep-winter": {
    best: [
      { name: "True Red", hex: "#C8102E" },
      { name: "Crimson", hex: "#A50F2D" },
      { name: "Burgundy", hex: "#6E1E30" },
      { name: "Plum", hex: "#6A1B4D" },
      { name: "Deep Raspberry", hex: "#9E1F55" },
      { name: "Magenta", hex: "#B3176F" },
      { name: "Fuchsia", hex: "#CC2A7E" },
      { name: "Royal Purple", hex: "#5A2D91" },
      { name: "Deep Violet", hex: "#4A2575" },
      { name: "Aubergine", hex: "#3E1E3A" },
      { name: "Royal Blue", hex: "#2649B3" },
      { name: "Cobalt", hex: "#0047AB" },
      { name: "Midnight Blue", hex: "#191970" },
      { name: "Navy", hex: "#1A2550" },
      { name: "Peacock", hex: "#00687A" },
      { name: "Deep Teal", hex: "#00575C" },
      { name: "Emerald", hex: "#00704A" },
      { name: "Pine Green", hex: "#01543F" },
      { name: "Evergreen", hex: "#1E4D2B" },
      { name: "Icy Pink", hex: "#F1D3E2" },
      { name: "Icy Blue", hex: "#D6E6F2" },
      { name: "Icy Mint", hex: "#D5F0E3" },
      { name: "Icy Lemon", hex: "#F3F0C2" },
      { name: "Icy Violet", hex: "#DCD3EE" },
    ],
    avoid: [
      { name: "Peach", hex: "#F5B88F" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Mustard", hex: "#BF9A4A" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Warm Beige", hex: "#D9BE94" },
      { name: "Orange", hex: "#F57B20" },
    ],
    neutrals: [
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Cool Grey", hex: "#8A8D93" },
      { name: "Charcoal", hex: "#333438" },
      { name: "Dark Espresso", hex: "#2A2024" },
      { name: "Dark Navy", hex: "#14213D" },
      { name: "Black", hex: "#000000" },
    ],
    metals: [
      { name: "Silver", hex: "#C0C3C8" },
      { name: "Platinum", hex: "#DCDDDF" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Gunmetal", hex: "#5A5D63" },
    ],
    metalsAvoid: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Copper", hex: "#B87333" },
    ],
    lips: [
      { name: "True Red", hex: "#C01C30" },
      { name: "Deep Berry", hex: "#7E1F45" },
      { name: "Burgundy Wine", hex: "#6A1A2E" },
    ],
    blush: [
      { name: "Cool Berry", hex: "#B5476E" },
      { name: "Plum Rose", hex: "#A44A6E" },
      { name: "Deep Rose", hex: "#C25A78" },
    ],
    eyes: [
      { name: "Charcoal", hex: "#3A3B40" },
      { name: "Deep Plum", hex: "#4A2340" },
      { name: "Navy", hex: "#1E2A55" },
    ],
    hair: [
      { name: "Cool Dark Brown", hex: "#2E2523" },
      { name: "Espresso", hex: "#2E201A" },
      { name: "Soft Black", hex: "#1E1C1E" },
    ],
    draping: {
      best: { name: "True Red", hex: "#C8102E" },
      worst: { name: "Mustard", hex: "#BF9A4A" },
    },
    highlights: [
      { name: "True Red", hex: "#C8102E" },
      { name: "Emerald", hex: "#00704A" },
      { name: "Cobalt", hex: "#0047AB" },
      { name: "Fuchsia", hex: "#CC2A7E" },
      { name: "Royal Purple", hex: "#5A2D91" },
      { name: "Charcoal", hex: "#333438" },
    ],
  },
  "true-winter": {
    best: [
      { name: "Blue Red", hex: "#C21E3A" },
      { name: "Cherry", hex: "#D0103A" },
      { name: "Burgundy Wine", hex: "#7A1530" },
      { name: "Cool Raspberry", hex: "#9E1F55" },
      { name: "Magenta", hex: "#B3176F" },
      { name: "Hot Pink", hex: "#E01E7E" },
      { name: "Plum", hex: "#6A1B4D" },
      { name: "Royal Purple", hex: "#5A2D91" },
      { name: "Violet", hex: "#7A2FB8" },
      { name: "Royal Blue", hex: "#2649B3" },
      { name: "Sapphire", hex: "#1A3F99" },
      { name: "Cobalt", hex: "#0047AB" },
      { name: "Cyan Blue", hex: "#0093C8" },
      { name: "Teal Blue", hex: "#00708A" },
      { name: "Turquoise", hex: "#00B2B8" },
      { name: "Jade Green", hex: "#00A88F" },
      { name: "Emerald", hex: "#00845A" },
      { name: "Pine", hex: "#01543F" },
      { name: "Lemon Yellow", hex: "#F2E14C" },
      { name: "Icy Pink", hex: "#F1D3E2" },
      { name: "Icy Blue", hex: "#D6E6F2" },
      { name: "Icy Mint", hex: "#D5F0E3" },
      { name: "Icy Lavender", hex: "#DCD3EE" },
      { name: "Silver Grey", hex: "#A8ACB3" },
    ],
    avoid: [
      { name: "Peach", hex: "#F5B88F" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Orange", hex: "#F57B20" },
      { name: "Olive", hex: "#7B7848" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Golden Brown", hex: "#8B5A2B" },
    ],
    neutrals: [
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Cool Grey", hex: "#8A8D93" },
      { name: "Pewter Grey", hex: "#6E7177" },
      { name: "Charcoal", hex: "#333438" },
      { name: "Navy", hex: "#1A2550" },
      { name: "Black", hex: "#000000" },
    ],
    metals: [
      { name: "Silver", hex: "#C0C3C8" },
      { name: "Platinum", hex: "#DCDDDF" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Polished Steel", hex: "#9EA2A8" },
    ],
    metalsAvoid: [
      { name: "Yellow Gold", hex: "#D4AF37" },
      { name: "Brass", hex: "#B5975A" },
    ],
    lips: [
      { name: "Blue Red", hex: "#C21E3A" },
      { name: "Cool Fuchsia", hex: "#C8227A" },
      { name: "Berry Wine", hex: "#7E1F45" },
    ],
    blush: [
      { name: "Cool Pink", hex: "#E08AAE" },
      { name: "Fuchsia Flush", hex: "#D0558E" },
      { name: "Plum Rose", hex: "#A44A6E" },
    ],
    eyes: [
      { name: "Charcoal", hex: "#3A3B40" },
      { name: "Navy", hex: "#1E2A55" },
      { name: "Silver Grey", hex: "#A8ACB3" },
    ],
    hair: [
      { name: "Cool Dark Brown", hex: "#2E2523" },
      { name: "Soft Black", hex: "#1E1C1E" },
      { name: "Blue Black", hex: "#121620" },
    ],
    draping: {
      best: { name: "Blue Red", hex: "#C21E3A" },
      worst: { name: "Camel", hex: "#C39D6F" },
    },
    highlights: [
      { name: "Blue Red", hex: "#C21E3A" },
      { name: "Cobalt", hex: "#0047AB" },
      { name: "Lemon Yellow", hex: "#F2E14C" },
      { name: "Hot Pink", hex: "#E01E7E" },
      { name: "Emerald", hex: "#00845A" },
      { name: "Charcoal", hex: "#333438" },
    ],
  },
  "bright-winter": {
    best: [
      { name: "Clear Red", hex: "#E0182D" },
      { name: "Watermelon Red", hex: "#F0425A" },
      { name: "Raspberry", hex: "#B5174F" },
      { name: "Hot Pink", hex: "#F0287E" },
      { name: "Shocking Pink", hex: "#FF3FA4" },
      { name: "Bright Magenta", hex: "#C8178A" },
      { name: "Bright Violet", hex: "#8A2BE2" },
      { name: "Purple", hex: "#6A2CA0" },
      { name: "Bright Periwinkle", hex: "#6A72E8" },
      { name: "Electric Blue", hex: "#2457D6" },
      { name: "Royal Blue", hex: "#1F45C2" },
      { name: "Cobalt", hex: "#0047AB" },
      { name: "Bright Navy", hex: "#1B2A6B" },
      { name: "Cyan", hex: "#00A3E0" },
      { name: "Bright Turquoise", hex: "#00C1C1" },
      { name: "Bright Teal", hex: "#008C95" },
      { name: "Emerald", hex: "#009B6A" },
      { name: "Bright Green", hex: "#00B050" },
      { name: "Lemon Yellow", hex: "#F7E52E" },
      { name: "Icy Pink", hex: "#F4CCE0" },
      { name: "Icy Blue", hex: "#D3E7F7" },
      { name: "Icy Mint", hex: "#CDF2E2" },
      { name: "Icy Lemon", hex: "#F6F3C0" },
      { name: "Icy Violet", hex: "#DED2F2" },
    ],
    avoid: [
      { name: "Dusty Rose", hex: "#C4A0A5" },
      { name: "Mushroom", hex: "#A08F7E" },
      { name: "Olive Drab", hex: "#6B6A3A" },
      { name: "Camel", hex: "#C39D6F" },
      { name: "Rust", hex: "#A65E3E" },
      { name: "Muted Sage", hex: "#9AA38C" },
    ],
    neutrals: [
      { name: "Pure White", hex: "#FFFFFF" },
      { name: "Light Cool Grey", hex: "#D0D2D6" },
      { name: "Medium Grey", hex: "#8A8C90" },
      { name: "Charcoal", hex: "#333438" },
      { name: "Ink Navy", hex: "#141E3C" },
      { name: "Black", hex: "#000000" },
    ],
    metals: [
      { name: "Polished Silver", hex: "#C7CBD1" },
      { name: "Platinum", hex: "#DCDDDF" },
      { name: "White Gold", hex: "#DDDBD2" },
      { name: "Chrome", hex: "#B4B8BE" },
    ],
    metalsAvoid: [
      { name: "Antique Gold", hex: "#B8963E" },
      { name: "Bronze", hex: "#8C6A43" },
    ],
    lips: [
      { name: "Clear Red", hex: "#D81E34" },
      { name: "Hot Fuchsia", hex: "#E0287E" },
      { name: "Bright Berry", hex: "#B01E5A" },
    ],
    blush: [
      { name: "Bright Pink", hex: "#F07AA8" },
      { name: "Cool Coral Pink", hex: "#F27A8E" },
      { name: "Raspberry Flush", hex: "#D0507A" },
    ],
    eyes: [
      { name: "Charcoal", hex: "#3A3B40" },
      { name: "Bright Navy", hex: "#1B2A6B" },
      { name: "Violet Plum", hex: "#5A2D7A" },
    ],
    hair: [
      { name: "Soft Black", hex: "#1E1C1E" },
      { name: "Dark Brown", hex: "#2E2321" },
      { name: "Cool Espresso", hex: "#3A2C2A" },
    ],
    draping: {
      best: { name: "Hot Pink", hex: "#F0287E" },
      worst: { name: "Mushroom", hex: "#A08F7E" },
    },
    highlights: [
      { name: "Hot Pink", hex: "#F0287E" },
      { name: "Bright Turquoise", hex: "#00C1C1" },
      { name: "Lemon Yellow", hex: "#F7E52E" },
      { name: "Bright Violet", hex: "#8A2BE2" },
      { name: "Emerald", hex: "#009B6A" },
      { name: "Charcoal", hex: "#333438" },
    ],
  },
};
